export default function () {
  return {
    signs: [
      {"subject":"A","images":"/abjad/A.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"B","images":"/abjad/B.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"C","images":"/abjad/C.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"D","images":"/abjad/D.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"E","images":"/abjad/E.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"F","images":"/abjad/F.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"G","images":"/abjad/G.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"H","images":"/abjad/H.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"I","images":"/abjad/I.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"J","images":"/abjad/J.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"K","images":"/abjad/K.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"L","images":"/abjad/L.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"M","images":"/abjad/M.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"N","images":"/abjad/N.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"O","images":"/abjad/O.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"P","images":"/abjad/P.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"Q","images":"/abjad/Q.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"R","images":"/abjad/R.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"S","images":"/abjad/S.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"T","images":"/abjad/T.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"U","images":"/abjad/U.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"V","images":"/abjad/V.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"W","images":"/abjad/W.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"X","images":"/abjad/X.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"Y","images":"/abjad/Y.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"Z","images":"/abjad/Z.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"1","images":"/angka/1.png","action":"lorem ipsum","type":"angka"},
      {"subject":"2","images":"/angka/2.png","action":"lorem ipsum","type":"angka"},
      {"subject":"3","images":"/angka/3.png","action":"lorem ipsum","type":"angka"},
      {"subject":"4","images":"/angka/4.png","action":"lorem ipsum","type":"angka"},
      {"subject":"5","images":"/angka/5.png","action":"lorem ipsum","type":"angka"},
      {"subject":"6","images":"/angka/6.png","action":"lorem ipsum","type":"angka"},
      {"subject":"7","images":"/angka/7.png","action":"lorem ipsum","type":"angka"},
      {"subject":"8","images":"/angka/8.png","action":"lorem ipsum","type":"angka"},
      {"subject":"9","images":"/angka/9.png","action":"lorem ipsum","type":"angka"},
      {"subject":"10","images":"/angka/10.png","action":"lorem ipsum","type":"angka"},
      {"subject":"100","images":"/angka/100.png","action":"lorem ipsum","type":"angka"},
      {"subject":"1000","images":"/angka/1000.png","action":"lorem ipsum","type":"angka"},
      {"subject":"1000000","images":"/angka/1000000.png","action":"lorem ipsum","type":"angka"},
      {"subject":"Aku","images":"/katagantidiri/aku.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"Engkau","images":"/katagantidiri/engkau.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"Kamu","images":"/katagantidiri/kamu.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"Saya","images":"/katagantidiri/saya.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"AlQuran","images":"/melayuislamberaja/AlQuran.jpg","action":"lorem ipsum","type":"mib"},
      {"subject":"Alhamdulillah","images":"/melayuislamberaja/Alhamdulillah.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Allah","images":"/melayuislamberaja/Allah.png","action":"lorem ipsum","type":"mib"},
      {"subject":"InsyaAllah","images":"/melayuislamberaja/InsyaAllah.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Masjid","images":"/melayuislamberaja/Masjid.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Solat","images":"/melayuislamberaja/Solat.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Syukur","images":"/melayuislamberaja/Syukur.jpg","action":"lorem ipsum","type":"mib"},
      {"subject":"disember","images":"/namabulan/disember.png","action":"lorem ipsum","type":"bulan"},
      {"subject":"januari","images":"/namabulan/januari.jpg","action":"lorem ipsum","type":"bulan"},
      {"subject":"sebulan","images":"/namabulan/sebulan.png","action":"lorem ipsum","type":"bulan"},
      {"subject":"tahun","images":"/namabulan/tahun.png","action":"lorem ipsum","type":"bulan"},
      {"subject":"ahad","images":"/namahari/ahad.png","action":"lorem ipsum","type":"hari"},
      {"subject":"isnin","images":"/namahari/isnin.png","action":"lorem ipsum","type":"hari"},
      {"subject":"selasa","images":"/namahari/selasa.png","action":"lorem ipsum","type":"hari"},
      {"subject":"rabu","images":"/namahari/rabu.png","action":"lorem ipsum","type":"hari"},
      {"subject":"khamis","images":"/namahari/khamis.png","action":"lorem ipsum","type":"hari"},
      {"subject":"jumaat","images":"/namahari/jumaat.png","action":"lorem ipsum","type":"hari"},
      {"subject":"sabtu","images":"/namahari/sabtu.png","action":"lorem ipsum","type":"hari"},
      {"subject":"hari","images":"/namahari/hari.jpg","action":"lorem ipsum","type":"hari"},
      {"subject":"seminggu","images":"/namahari/seminggu.png","action":"lorem ipsum","type":"hari"},
      {"subject":"abang","images":"/orang/abang.png","action":"lorem ipsum","type":"orang"},
      {"subject":"adik lelaki","images":"/orang/adik lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"adik perempuan","images":"/orang/adik perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"amah","images":"/orang/amah.png","action":"lorem ipsum","type":"orang"},
      {"subject":"anak lelaki","images":"/orang/anak lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"anak perempuan","images":"/orang/anak perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"bapa","images":"/orang/bapa.png","action":"lorem ipsum","type":"orang"},
      {"subject":"bos","images":"/orang/bos.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"cikgu","images":"/orang/cikgu.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"doktor","images":"/orang/doktor.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"emak","images":"/orang/emak.png","action":"lorem ipsum","type":"orang"},
      {"subject":"isteri","images":"/orang/isteri.png","action":"lorem ipsum","type":"orang"},
      {"subject":"jurubahasa","images":"/orang/jurubahasa.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"jururawat","images":"/orang/jururawat.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"kakak","images":"/orang/kakak.png","action":"lorem ipsum","type":"orang"},
      {"subject":"kanak-kanak","images":"/orang/kanak-kanak.png","action":"lorem ipsum","type":"orang"},
      {"subject":"kawan","images":"/orang/kawan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"keluarga","images":"/orang/keluarga.png","action":"lorem ipsum","type":"orang"},
      {"subject":"lelaki","images":"/orang/lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"nenek lelaki","images":"/orang/nenek lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"nenek perempuan","images":"/orang/nenek perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"orang","images":"/orang/orang.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"pelajar","images":"/orang/pelajar.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"pengerusi","images":"/orang/pengerusi.png","action":"lorem ipsum","type":"orang"},
      {"subject":"pensyarah","images":"/orang/pensyarah.png","action":"lorem ipsum","type":"orang"},
      {"subject":"penyelia","images":"/orang/penyelia.png","action":"lorem ipsum","type":"orang"},
      {"subject":"perempuan","images":"/orang/perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"polis","images":"/orang/polis.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"setiausaha","images":"/orang/setiausaha.png","action":"lorem ipsum","type":"orang"},
      {"subject":"suami","images":"/orang/suami.png","action":"lorem ipsum","type":"orang"},
      {"subject":"ambuyat","images":"/perkataanbrunei/ambuyat.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"ardam","images":"/perkataanbrunei/ardam.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"bahulu","images":"/perkataanbrunei/bahulu.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"buah manggis","images":"/perkataanbrunei/buah manggis.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"cacah","images":"/perkataanbrunei/cacah.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"durian kuning","images":"/perkataanbrunei/durian kuning.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"durian putih","images":"/perkataanbrunei/durian putih.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"kelupis","images":"/perkataanbrunei/kelupis.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"lalap daging","images":"/perkataanbrunei/lalap daging.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"penyaram","images":"/perkataanbrunei/penyaram.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"pulut panggang","images":"/perkataanbrunei/pulut panggang.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"tapai","images":"/perkataanbrunei/tapai.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"wajid","images":"/perkataanbrunei/wajid.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"ada","images":"/seringdigunakan/ada.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"arah","images":"/seringdigunakan/arah.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"baca","images":"/seringdigunakan/baca.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"baru","images":"/seringdigunakan/baru.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"benci","images":"/seringdigunakan/benci.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"berangan","images":"/seringdigunakan/berangan.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"berdiri","images":"/seringdigunakan/berdiri.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"berumur","images":"/seringdigunakan/berumur.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"besar","images":"/seringdigunakan/besar.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"betul","images":"/seringdigunakan/betul.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"buku","images":"/seringdigunakan/buku.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"cantik","images":"/seringdigunakan/cantik.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"cermin","images":"/seringdigunakan/cermin.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"comel","images":"/seringdigunakan/comel.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"duduk","images":"/seringdigunakan/duduk.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"duit","images":"/seringdigunakan/duit.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"emas","images":"/seringdigunakan/emas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"fikir","images":"/seringdigunakan/fikir.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"gembira","images":"/seringdigunakan/gembira.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"hidup","images":"/seringdigunakan/hidup.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ikan","images":"/seringdigunakan/ikan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"jangan","images":"/seringdigunakan/jangan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kapalterbang","images":"/seringdigunakan/kapalterbang.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kasut","images":"/seringdigunakan/kasut.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kecil","images":"/seringdigunakan/kecil.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"keluar","images":"/seringdigunakan/keluar.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kereta","images":"/seringdigunakan/kereta.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kering","images":"/seringdigunakan/kering.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kertas","images":"/seringdigunakan/kertas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kerusi","images":"/seringdigunakan/kerusi.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ketawa","images":"/seringdigunakan/ketawa.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kotak bilik","images":"/seringdigunakan/kotak bilik.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kotor","images":"/seringdigunakan/kotor.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"lagi","images":"/seringdigunakan/lagi.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"makan","images":"/seringdigunakan/makan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"makanan","images":"/seringdigunakan/makanan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"malam","images":"/seringdigunakan/malam.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"malas","images":"/seringdigunakan/malas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"masuk","images":"/seringdigunakan/masuk.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"minum","images":"/seringdigunakan/minum.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"nama","images":"/seringdigunakan/nama.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"nasi","images":"/seringdigunakan/nasi.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ofis","images":"/seringdigunakan/ofis.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"pagi","images":"/seringdigunakan/pagi.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"pandai","images":"/seringdigunakan/pandai.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"perak","images":"/seringdigunakan/perak.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"percuma","images":"/seringdigunakan/percuma.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"pintu","images":"/seringdigunakan/pintu.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"piring","images":"/seringdigunakan/piring.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"punya milik","images":"/seringdigunakan/punya milik.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"rumah sakit","images":"/seringdigunakan/rumah sakit.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"rumah","images":"/seringdigunakan/rumah.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sakit","images":"/seringdigunakan/sakit.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"salah","images":"/seringdigunakan/salah.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sedih","images":"/seringdigunakan/sedih.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sekolah","images":"/seringdigunakan/sekolah.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"senyum","images":"/seringdigunakan/senyum.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sibuk","images":"/seringdigunakan/sibuk.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"stokin","images":"/seringdigunakan/stokin.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"suka","images":"/seringdigunakan/suka.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tandas","images":"/seringdigunakan/tandas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tengahari","images":"/seringdigunakan/tengahari.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tidur","images":"/seringdigunakan/tidur.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tinggal","images":"/seringdigunakan/tinggal.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tipu","images":"/seringdigunakan/tipu.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tukar","images":"/seringdigunakan/tukar.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tulis","images":"/seringdigunakan/tulis.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tunggu","images":"/seringdigunakan/tunggu.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tutup","images":"/seringdigunakan/tutup.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ya","images":"/seringdigunakan/ya.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"apa","images":"/tanya/apa.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"bila","images":"/tanya/bila.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"kenapa mengapa","images":"/tanya/kenapa mengapa.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"mana kemana","images":"/tanya/mana kemana.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"siapa","images":"/tanya/siapa.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"assalamualaikum","images":"/ucapanharian/assalamualaikum.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"bismillah","images":"/ucapanharian/bismillah.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"brunei","images":"/ucapanharian/brunei.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"hello","images":"/ucapanharian/hello.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"waalaikumsalam","images":"/ucapanharian/waalaikumussalam.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"biru lelaki","images":"/warna/biru lelaki.png","action":"lorem ipsum","type":"warna"},
      {"subject":"biru perempuan","images":"/warna/biru perempuan.png","action":"lorem ipsum","type":"warna"},
      {"subject":"coklat","images":"/warna/coklat.png","action":"lorem ipsum","type":"warna"},
      {"subject":"hijau","images":"/warna/hijau.png","action":"lorem ipsum","type":"warna"},
      {"subject":"hitam","images":"/warna/hitam.png","action":"lorem ipsum","type":"warna"},
      {"subject":"jingga","images":"/warna/jingga.png","action":"lorem ipsum","type":"warna"},
      {"subject":"kelabu","images":"/warna/kelabu.png","action":"lorem ipsum","type":"warna"},
      {"subject":"kuning","images":"/warna/kuning.png","action":"lorem ipsum","type":"warna"},
      {"subject":"merah jambu","images":"/warna/merah jambu.png","action":"lorem ipsum","type":"warna"},
      {"subject":"merah","images":"/warna/merah.png","action":"lorem ipsum","type":"warna"},
      {"subject":"putih","images":"/warna/putih.png","action":"lorem ipsum","type":"warna"},
      {"subject":"ungu","images":"/warna/ungu.png","action":"lorem ipsum","type":"warna"},
      {"subject":"warna","images":"/warna/warna.png","action":"lorem ipsum","type":"warna"}
      ]
  }
}
