export default function () {
  return {
    signs: [
      {"subject":"A","images":"statics/abjad/A.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"B","images":"statics/abjad/B.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"C","images":"statics/abjad/C.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"D","images":"statics/abjad/D.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"E","images":"statics/abjad/E.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"F","images":"statics/abjad/F.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"G","images":"statics/abjad/G.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"H","images":"statics/abjad/H.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"I","images":"statics/abjad/I.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"J","images":"statics/abjad/J.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"K","images":"statics/abjad/K.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"L","images":"statics/abjad/L.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"M","images":"statics/abjad/M.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"N","images":"statics/abjad/N.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"O","images":"statics/abjad/O.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"P","images":"statics/abjad/P.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"Q","images":"statics/abjad/Q.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"R","images":"statics/abjad/R.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"S","images":"statics/abjad/S.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"T","images":"statics/abjad/T.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"U","images":"statics/abjad/U.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"V","images":"statics/abjad/V.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"W","images":"statics/abjad/W.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"X","images":"statics/abjad/X.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"Y","images":"statics/abjad/Y.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"Z","images":"statics/abjad/Z.png","action":"lorem ipsum","type":"abjad"},
      {"subject":"1","images":"statics/angka/1.png","action":"lorem ipsum","type":"angka"},
      {"subject":"2","images":"statics/angka/2.png","action":"lorem ipsum","type":"angka"},
      {"subject":"3","images":"statics/angka/3.png","action":"lorem ipsum","type":"angka"},
      {"subject":"4","images":"statics/angka/4.png","action":"lorem ipsum","type":"angka"},
      {"subject":"5","images":"statics/angka/5.png","action":"lorem ipsum","type":"angka"},
      {"subject":"6","images":"statics/angka/6.png","action":"lorem ipsum","type":"angka"},
      {"subject":"7","images":"statics/angka/7.png","action":"lorem ipsum","type":"angka"},
      {"subject":"8","images":"statics/angka/8.png","action":"lorem ipsum","type":"angka"},
      {"subject":"9","images":"statics/angka/9.png","action":"lorem ipsum","type":"angka"},
      {"subject":"10","images":"statics/angka/10.png","action":"lorem ipsum","type":"angka"},
      {"subject":"100","images":"statics/angka/100.png","action":"lorem ipsum","type":"angka"},
      {"subject":"1000","images":"statics/angka/1000.png","action":"lorem ipsum","type":"angka"},
      {"subject":"1000000","images":"statics/angka/1000000.png","action":"lorem ipsum","type":"angka"},
      {"subject":"Aku","images":"statics/katagantidiri/aku.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"Engkau","images":"statics/katagantidiri/engkau.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"Kamu","images":"statics/katagantidiri/kamu.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"Saya","images":"statics/katagantidiri/saya.png","action":"lorem ipsum","type":"kata ganti diri"},
      {"subject":"AlQuran","images":"statics/melayuislamberaja/AlQuran.jpg","action":"lorem ipsum","type":"mib"},
      {"subject":"Alhamdulillah","images":"statics/melayuislamberaja/Alhamdulillah.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Allah","images":"statics/melayuislamberaja/Allah.png","action":"lorem ipsum","type":"mib"},
      {"subject":"InsyaAllah","images":"statics/melayuislamberaja/InsyaAllah.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Masjid","images":"statics/melayuislamberaja/Masjid.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Solat","images":"statics/melayuislamberaja/Solat.png","action":"lorem ipsum","type":"mib"},
      {"subject":"Syukur","images":"statics/melayuislamberaja/Syukur.jpg","action":"lorem ipsum","type":"mib"},
      {"subject":"disember","images":"statics/namabulan/disember.png","action":"lorem ipsum","type":"bulan"},
      {"subject":"januari","images":"statics/namabulan/januari.jpg","action":"lorem ipsum","type":"bulan"},
      {"subject":"sebulan","images":"statics/namabulan/sebulan.png","action":"lorem ipsum","type":"bulan"},
      {"subject":"tahun","images":"statics/namabulan/tahun.png","action":"lorem ipsum","type":"bulan"},
      {"subject":"ahad","images":"statics/namahari/ahad.png","action":"lorem ipsum","type":"hari"},
      {"subject":"isnin","images":"statics/namahari/isnin.png","action":"lorem ipsum","type":"hari"},
      {"subject":"selasa","images":"statics/namahari/selasa.png","action":"lorem ipsum","type":"hari"},
      {"subject":"rabu","images":"statics/namahari/rabu.png","action":"lorem ipsum","type":"hari"},
      {"subject":"khamis","images":"statics/namahari/khamis.png","action":"lorem ipsum","type":"hari"},
      {"subject":"jumaat","images":"statics/namahari/jumaat.png","action":"lorem ipsum","type":"hari"},
      {"subject":"sabtu","images":"statics/namahari/sabtu.png","action":"lorem ipsum","type":"hari"},
      {"subject":"hari","images":"statics/namahari/hari.jpg","action":"lorem ipsum","type":"hari"},
      {"subject":"seminggu","images":"statics/namahari/seminggu.png","action":"lorem ipsum","type":"hari"},
      {"subject":"abang","images":"statics/orang/abang.png","action":"lorem ipsum","type":"orang"},
      {"subject":"adik lelaki","images":"statics/orang/adik lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"adik perempuan","images":"statics/orang/adik perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"amah","images":"statics/orang/amah.png","action":"lorem ipsum","type":"orang"},
      {"subject":"anak lelaki","images":"statics/orang/anak lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"anak perempuan","images":"statics/orang/anak perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"bapa","images":"statics/orang/bapa.png","action":"lorem ipsum","type":"orang"},
      {"subject":"bos","images":"statics/orang/bos.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"cikgu","images":"statics/orang/cikgu.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"doktor","images":"statics/orang/doktor.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"emak","images":"statics/orang/emak.png","action":"lorem ipsum","type":"orang"},
      {"subject":"isteri","images":"statics/orang/isteri.png","action":"lorem ipsum","type":"orang"},
      {"subject":"jurubahasa","images":"statics/orang/jurubahasa.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"jururawat","images":"statics/orang/jururawat.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"kakak","images":"statics/orang/kakak.png","action":"lorem ipsum","type":"orang"},
      {"subject":"kanak-kanak","images":"statics/orang/kanak-kanak.png","action":"lorem ipsum","type":"orang"},
      {"subject":"kawan","images":"statics/orang/kawan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"keluarga","images":"statics/orang/keluarga.png","action":"lorem ipsum","type":"orang"},
      {"subject":"lelaki","images":"statics/orang/lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"nenek lelaki","images":"statics/orang/nenek lelaki.png","action":"lorem ipsum","type":"orang"},
      {"subject":"nenek perempuan","images":"statics/orang/nenek perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"orang","images":"statics/orang/orang.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"pelajar","images":"statics/orang/pelajar.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"pengerusi","images":"statics/orang/pengerusi.png","action":"lorem ipsum","type":"orang"},
      {"subject":"pensyarah","images":"statics/orang/pensyarah.png","action":"lorem ipsum","type":"orang"},
      {"subject":"penyelia","images":"statics/orang/penyelia.png","action":"lorem ipsum","type":"orang"},
      {"subject":"perempuan","images":"statics/orang/perempuan.png","action":"lorem ipsum","type":"orang"},
      {"subject":"polis","images":"statics/orang/polis.jpg","action":"lorem ipsum","type":"orang"},
      {"subject":"setiausaha","images":"statics/orang/setiausaha.png","action":"lorem ipsum","type":"orang"},
      {"subject":"suami","images":"statics/orang/suami.png","action":"lorem ipsum","type":"orang"},
      {"subject":"ambuyat","images":"statics/perkataanbrunei/ambuyat.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"ardam","images":"statics/perkataanbrunei/ardam.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"bahulu","images":"statics/perkataanbrunei/bahulu.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"buah manggis","images":"statics/perkataanbrunei/buah manggis.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"cacah","images":"statics/perkataanbrunei/cacah.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"durian kuning","images":"statics/perkataanbrunei/durian kuning.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"durian putih","images":"statics/perkataanbrunei/durian putih.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"kelupis","images":"statics/perkataanbrunei/kelupis.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"lalap daging","images":"statics/perkataanbrunei/lalap daging.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"penyaram","images":"statics/perkataanbrunei/penyaram.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"pulut panggang","images":"statics/perkataanbrunei/pulut panggang.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"tapai","images":"statics/perkataanbrunei/tapai.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"wajid","images":"statics/perkataanbrunei/wajid.png","action":"lorem ipsum","type":"brunei"},
      {"subject":"ada","images":"statics/seringdigunakan/ada.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"arah","images":"statics/seringdigunakan/arah.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"baca","images":"statics/seringdigunakan/baca.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"baru","images":"statics/seringdigunakan/baru.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"benci","images":"statics/seringdigunakan/benci.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"berangan","images":"statics/seringdigunakan/berangan.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"berdiri","images":"statics/seringdigunakan/berdiri.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"berumur","images":"statics/seringdigunakan/berumur.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"besar","images":"statics/seringdigunakan/besar.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"betul","images":"statics/seringdigunakan/betul.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"buku","images":"statics/seringdigunakan/buku.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"cantik","images":"statics/seringdigunakan/cantik.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"cermin","images":"statics/seringdigunakan/cermin.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"comel","images":"statics/seringdigunakan/comel.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"duduk","images":"statics/seringdigunakan/duduk.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"duit","images":"statics/seringdigunakan/duit.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"emas","images":"statics/seringdigunakan/emas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"fikir","images":"statics/seringdigunakan/fikir.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"gembira","images":"statics/seringdigunakan/gembira.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"hidup","images":"statics/seringdigunakan/hidup.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ikan","images":"statics/seringdigunakan/ikan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"jangan","images":"statics/seringdigunakan/jangan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kapalterbang","images":"statics/seringdigunakan/kapalterbang.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kasut","images":"statics/seringdigunakan/kasut.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kecil","images":"statics/seringdigunakan/kecil.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"keluar","images":"statics/seringdigunakan/keluar.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kereta","images":"statics/seringdigunakan/kereta.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kering","images":"statics/seringdigunakan/kering.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kertas","images":"statics/seringdigunakan/kertas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kerusi","images":"statics/seringdigunakan/kerusi.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ketawa","images":"statics/seringdigunakan/ketawa.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kotak bilik","images":"statics/seringdigunakan/kotak bilik.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"kotor","images":"statics/seringdigunakan/kotor.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"lagi","images":"statics/seringdigunakan/lagi.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"makan","images":"statics/seringdigunakan/makan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"makanan","images":"statics/seringdigunakan/makanan.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"malam","images":"statics/seringdigunakan/malam.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"malas","images":"statics/seringdigunakan/malas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"masuk","images":"statics/seringdigunakan/masuk.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"minum","images":"statics/seringdigunakan/minum.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"nama","images":"statics/seringdigunakan/nama.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"nasi","images":"statics/seringdigunakan/nasi.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ofis","images":"statics/seringdigunakan/ofis.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"pagi","images":"statics/seringdigunakan/pagi.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"pandai","images":"statics/seringdigunakan/pandai.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"perak","images":"statics/seringdigunakan/perak.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"percuma","images":"statics/seringdigunakan/percuma.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"pintu","images":"statics/seringdigunakan/pintu.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"piring","images":"statics/seringdigunakan/piring.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"punya milik","images":"statics/seringdigunakan/punya milik.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"rumah sakit","images":"statics/seringdigunakan/rumah sakit.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"rumah","images":"statics/seringdigunakan/rumah.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sakit","images":"statics/seringdigunakan/sakit.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"salah","images":"statics/seringdigunakan/salah.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sedih","images":"statics/seringdigunakan/sedih.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sekolah","images":"statics/seringdigunakan/sekolah.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"senyum","images":"statics/seringdigunakan/senyum.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"sibuk","images":"statics/seringdigunakan/sibuk.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"stokin","images":"statics/seringdigunakan/stokin.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"suka","images":"statics/seringdigunakan/suka.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tandas","images":"statics/seringdigunakan/tandas.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tengahari","images":"statics/seringdigunakan/tengahari.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tidur","images":"statics/seringdigunakan/tidur.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tinggal","images":"statics/seringdigunakan/tinggal.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tipu","images":"statics/seringdigunakan/tipu.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tukar","images":"statics/seringdigunakan/tukar.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tulis","images":"statics/seringdigunakan/tulis.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tunggu","images":"statics/seringdigunakan/tunggu.jpg","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"tutup","images":"statics/seringdigunakan/tutup.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"ya","images":"statics/seringdigunakan/ya.png","action":"lorem ipsum","type":"sering digunakan"},
      {"subject":"apa","images":"statics/tanya/apa.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"bila","images":"statics/tanya/bila.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"kenapa mengapa","images":"statics/tanya/kenapa mengapa.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"mana kemana","images":"statics/tanya/mana kemana.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"siapa","images":"statics/tanya/siapa.png","action":"lorem ipsum","type":"tanya"},
      {"subject":"assalamualaikum","images":"statics/ucapanharian/assalamualaikum.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"bismillah","images":"statics/ucapanharian/bismillah.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"brunei","images":"statics/ucapanharian/brunei.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"hello","images":"statics/ucapanharian/hello.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"waalaikumsalam","images":"statics/ucapanharian/waalaikumussalam.png","action":"lorem ipsum","type":"ucapan harian"},
      {"subject":"biru lelaki","images":"statics/warna/biru lelaki.png","action":"lorem ipsum","type":"warna"},
      {"subject":"biru perempuan","images":"statics/warna/biru perempuan.png","action":"lorem ipsum","type":"warna"},
      {"subject":"coklat","images":"statics/warna/coklat.png","action":"lorem ipsum","type":"warna"},
      {"subject":"hijau","images":"statics/warna/hijau.png","action":"lorem ipsum","type":"warna"},
      {"subject":"hitam","images":"statics/warna/hitam.png","action":"lorem ipsum","type":"warna"},
      {"subject":"jingga","images":"statics/warna/jingga.png","action":"lorem ipsum","type":"warna"},
      {"subject":"kelabu","images":"statics/warna/kelabu.png","action":"lorem ipsum","type":"warna"},
      {"subject":"kuning","images":"statics/warna/kuning.png","action":"lorem ipsum","type":"warna"},
      {"subject":"merah jambu","images":"statics/warna/merah jambu.png","action":"lorem ipsum","type":"warna"},
      {"subject":"merah","images":"statics/warna/merah.png","action":"lorem ipsum","type":"warna"},
      {"subject":"putih","images":"statics/warna/putih.png","action":"lorem ipsum","type":"warna"},
      {"subject":"ungu","images":"statics/warna/ungu.png","action":"lorem ipsum","type":"warna"},
      {"subject":"warna","images":"statics/warna/warna.png","action":"lorem ipsum","type":"warna"}
      ]
  }
}
