name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1.4.2
        with:
            node-version: '12'
        working-directory: bsl
        run: |
          npm install
          npx quasar build -m capacitor -T android --skip-pkg
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        run: cd bsl/src-capacitor/android
        with:
          args: "./gradlew assembleDebug"
      