name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
    tags: 'v*'
  pull_request:
    branches: [ master, dev ]
    tags: 'v*'

jobs:
  build-capacitor:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl

    strategy:
      matrix:
        node-version: [12.x]
#         node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx quasar build -m capacitor -T android --skip-pkg
      - run: chmod +x ./src-capacitor/android/gradlew
      - name: Gradle Android
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: ./bsl/src-capacitor/android/gradlew --project-dir=./bsl/src-capacitor/android assembleDebug
      - run: zip -r ../bsl-android-debug.zip ./src-capacitor/android/app/build/outputs/apk/debug/
    
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: draft-release
          release_name: Test Release
          body: Automated Deployment
          draft: false
          prerelease: false
          
      - name: Upload a Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bsl-android-debug.zip
          asset_name: bsl-android-debug.zip
          asset_content_type: appliction/zip
