name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
        name: Set up NodeJS ${{ matrix.node-version }}
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: cd bsl && npm install
      - name: Setup JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Build APK
        run: cd bsl && quasar build --mode capacitor --target android
