name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-capacitor:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl

    strategy:
      matrix:
        node-version: [12.x]
#         node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx quasar build -m capacitor -T android --skip-pkg
      - run: chmod +x ./src-capacitor/android/gradlew
      - name: Gradle Android
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: ./bsl/src-capacitor/android/gradlew --project-dir=./bsl/src-capacitor/android assembleDebug
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
          file: bsl/dist/capacitor/*
          # If you need to overwrite existing files, add overwrite: true to the with.
          overwrite: true
          # The resultant deployment is a draft Release that only repository collaborators can see. This gives you an opportunity to examine and edit the draft release.
          draft: true
          # The resultant deployment is a Prerelease. This gives you an opportunity to examine and edit the prerelease.
          prerelease: true
          # With tags: true, your Releases deployment will trigger if and only if the build is a tagged build.
          tags: false
          # Only work on these branches(splited by semicolon), set to nothing to accept all branches.
          # With verbose: true, be verbose.
          verbose: true
