name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
    tags: 'v*'
  pull_request:
    branches: [ master, dev ]
    tags: 'v*'

jobs:
  build-capacitor:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl

    strategy:
      matrix:
        node-version: [12.x]
#         node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx quasar build -m capacitor -T android --skip-pkg
      - run: chmod +x ./src-capacitor/android/gradlew
      - name: Gradle Android
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: ./bsl/src-capacitor/android/gradlew --project-dir=./bsl/src-capacitor/android assembleDebug
      - run: zip -r bsl-android-debug-${{github.GITHUB_REF}}.zip ./src-capacitor/android/app/build/outputs/apk/debug/
    
      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name: ${{ github.GITHUB_REF }}
          # The name of the release. For example, `Release v1.0.1`
          release_name: Release ${{ github.GITHUB_REF }}
          # Text describing the contents of the tag.
          body: Automated Deployment
          # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
          draft: true
          # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
          prerelease: false
          
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          # The URL for uploading assets to the release
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # The path to the asset you want to upload
          asset_path: ./bsl-android-debug-${{github.GITHUB_REF}}.zip
          # The name of the asset you want to upload
          asset_name: bsl-android-debug-${{github.GITHUB_REF}}.zip
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: appliction/zip
