name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-capacitor:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx quasar build -m capacitor -T android --skip-pkg
      
  build-android:
    needs: [build-capacitor]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl/src-capacitor/android
        
    steps:
      - uses: actions/checkout@v2
      - name: Gradle Android
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: ./bsl/src-capacitor/android/gradlew assembleDebug
