name: Quasar Android Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Set up Gradle
        uses: Raul6469/android-gradle-action@2.0.0
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        working-directory: bsl
        run: npm install
      - name: Start Quasar Android Build
        working-directory: bsl
        run: npx quasar build --mode capacitor --target android
