name: Quasar iOS Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-capacitor:
    runs-on: macos-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx quasar build -m capacitor -T ios --skip-pkg
        
      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v0.5.0
        with:
          # Project path
          project-path: bsl/src-capacitor/ios/App/App.xcodeproj
          # Base64 encoded p12 file
          p12-base64: ${{ secrets.P12_BASE64 }}
          # Base64 encoded mobileprovision file
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: bsl/src-capacitor/ios/App/App.xcworkspace
          export-method: development
          configuration: Debug
